### ISSUE TITLE
No longer able to download mappings

### ISSUE THREAD

**Issue by mrcorpz** [egold555/ReplaceModsWithForgeCSVMappingsGUI#10]
Since MCPBot shutdown, the program is no longer able to download mappings,

**Comment by mrcorpz** [comment]
[ReplaceModsWithForgeCSVMappingsGUIfixed.zip](https://github.com/egold555/ReplaceModsWithForgeCSVMappingsGUI/files/7910815/ReplaceModsWithForgeCSVMappingsGUIfixed.zip)

this build works but it need to be used with java 16 (idk my pc bugs out)

**Comment by egold555** [comment]
I've finally found some time to update the program. You can download the new version here: https://github.com/egold555/ReplaceModsWithForgeCSVMappingsGUI/raw/master/Releases/ReplaceModsWithForgeCSVMappingsGUI%20v1.2.jar

**Comment by HausemasterIssue** [comment]
@egold555 

![image](https://user-images.githubusercontent.com/90464553/151981455-a8b1a110-ca62-414d-a41f-ec1e725f8d61.png)

I don't think your new version works correctly.

**Comment by egold555** [comment]
I'm not sure. That's weird. I tested every version before I published it and it seemed to work. Can you manually visit that url and confirm you can reach that server?

**Comment by HausemasterIssue** [comment]
@egold555 

![image](https://user-images.githubusercontent.com/90464553/152228498-fad4e09c-f744-4457-bd73-2e54e1633387.png)

This is the webpage that shows up when I type in that link (http://export.mcpbot.golde.org/mcp_stable/39-1.12/mcp_stable-39-1.12.zip.zip). However, .zip is duplicated, if you remove the last .zip to get (http://export.mcpbot.golde.org/mcp_stable/39-1.12/mcp_stable-39-1.12.zip) then it works. You might want to check the URL your program goes to.

**Comment by egold555** [comment]
> @egold555
> 
> ![image](https://user-images.githubusercontent.com/90464553/152228498-fad4e09c-f744-4457-bd73-2e54e1633387.png)
> 
> This is the webpage that shows up when I type in that link (http://export.mcpbot.golde.org/mcp_stable/39-1.12/mcp_stable-39-1.12.zip.zip). However, .zip is duplicated, if you remove the last .zip to get (http://export.mcpbot.golde.org/mcp_stable/39-1.12/mcp_stable-39-1.12.zip) then it works. You might want to check the URL your program goes to.

The double .zip error is just a graphical issue on my end in the UI. Whoops https://github.com/egold555/ReplaceModsWithForgeCSVMappingsGUI/blob/master/src/org/golde/java/rmwfcsvmg/ThreadReplaceCSV.java#L43

As for now being able to download, I don't know because they all work fine on my machine. Ill try to do some more testing, and if I ever decide to work more on this I should provide better error messages.

**Comment by HausemasterIssue** [comment]
@egold555 Try to make the link https instead of http. I've had things my computer couldn't get because they were http, not too sure why but try out https in the link.
