### ISSUE TITLE
Application won't open due to no manifest

### ISSUE THREAD

**Issue by DavidIlie** [egold555/ReplaceModsWithForgeCSVMappingsGUI#6]
Hello, I was trying to decompile Optifine for MCP but whenever I tried launching the application, it turned off!

After many tries I tried launching the app with command prompt (java -jar app.jar) and I got a error saying there is no manifest. 

After that I put the profit in the Java IDE and it worked for some reason (Perhaps IntelIiJ Generating a manifest) but anyway, just wanted to point this out.

Have a nice day,
Albastru

**Comment by egold555** [comment]
Its a Gui application, it does not work via the command line, but that something I could add. Also this program won't work with Optifine fully because I have not found a way to read certain files and rename everything in them #3

**Comment by DavidIlie** [comment]
No I didn't mean that, I just wanted to run the GUI app via the command line to see the console and I found that error there. I'm just saying that maybe you need to rebuild it or something

Sorry if I didn't make myself clear and also I managed to decompile optifine for my client.

Again, have a nice day,
Albastru

**Comment by egold555** [comment]
It should open if you downloaded it from the releases folder.. You can this new version I just released.
https://github.com/egold555/ReplaceModsWithForgeCSVMappingsGUI/raw/master/Releases/ReplaceModsWithForgeCSVMappingsGUI%20v1.2.jar
