### ISSUE TITLE
The program wont open

### ISSUE THREAD

**Issue by Subhamgoesweee** [egold555/ReplaceModsWithForgeCSVMappingsGUI#8]
Well i did everything but the program didnt open

**Comment by TheBeaconCrafter** [comment]
Same. Maybe other java ersion?

**Comment by TheBeaconCrafter** [comment]
Oh, just found it LOL. Go to the code and select Releases (The Folder, nut the Github thing) and download Version 1.1. 1.1 is not in the Releases of Github

**Comment by signalm** [comment]
Thank you

**Comment by egold555** [comment]
I've finally found some time to update the program. You can download the new version here: https://github.com/egold555/ReplaceModsWithForgeCSVMappingsGUI/raw/master/Releases/ReplaceModsWithForgeCSVMappingsGUI%20v1.2.jar
